# Generated by Django 3.1.1 on 2020-09-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200926_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_front_page',
            field=models.BooleanField(default=False, verbose_name='Set as front page'),
        ),
    ]
